### ISSUE TITLE
Provider assumes apt for linux os

### ISSUE THREAD

**Issue by gustaff-weldon** [cloudbase/garm-provider-gcp#22]
Currently, the provider assumes that runner image for linux contains `apt`
https://github.com/cloudbase/garm-provider-gcp/blob/494d2ef6434f2d504a1f6674d2e7b3f832c38b9a/internal/spec/spec.go#L296-L307

This makes it difficult to use custom runner images based eg. on Alpine

**Comment by gabriel-samfira** [comment]
Alpine might not work. Not sure if the gh runner supoorts it.

**Comment by fabi200123** [comment]
Hello there! 
The PR #25 will update the way the GCP provider works for linux. Now it will allows just linux images that have cloud-init on them so the provider will not assume anymore that `apt` is installed on the instances.

**Comment by gabriel-samfira** [comment]
Closed via #25
