### ISSUE TITLE
Enhancement Requests: Disk, DisplayDevice, ServiceAccounts, and Additional Logging

### ISSUE THREAD

**Issue by Hdom** [cloudbase/garm-provider-gcp#31]
**- Attached disk: Add spec.CustomLabels and make DiskType configurable.** 

Currently our GCP VMs default to `pd-standard` which is HDD and would like to leverage `pd-balanced` or `pd-ssd`. Also the CustomLabels should be passed in to the disk as it generates a separate resource for disks.
```go
Disks:       generateBootDisk(spec.DiskSize, spec.BootstrapParams.Image, spec.SourceSnapshot, spec.CustomLabels, &spec.DiskType),
```

**- DisplayDevice: Add ability to enable virtual display device.** 

Something like this:
```go
DisplayDevice: &computepb.DisplayDevice{
    EnableDisplay: proto.Bool(spec.DisplayDevice),
},
```

**- Service Accounts: Add ability to attach a service account to the VM and configure scopes needed for metrics and logging**

For example:
```go
serviceAccounts := []*computepb.ServiceAccount{}

if spec.ServiceAccount != "" {
	serviceAccounts = []*computepb.ServiceAccount{
		{
			Email: proto.String(spec.ServiceAccount),
			Scopes: []string{
				"https://www.googleapis.com/auth/devstorage.read_only",
				"https://www.googleapis.com/auth/logging.write",
				"https://www.googleapis.com/auth/monitoring.write",
				"https://www.googleapis.com/auth/service.management.readonly",
				"https://www.googleapis.com/auth/servicecontrol",
				"https://www.googleapis.com/auth/trace.append",
			},
		},
	}
}

inst := &computepb.Instance{
...
    ServiceAccounts: serviceAccounts,
...
}
```

**- Add additional logging to provider.**

When a runner fails to `install` it reports back and logging information can be seen in `garm-cli runner show <runner>`  "Status Updates", but if it fails to list, create, start, stop, or delete (due to network, permissions, or some configuration issue) that information is never output to log.

**- Add runner software caching to windows startup script.**

There was a recent github outage that caused degraded download speeds causing our windows VMs to fail to download the runner software before the timeout period. Could we add the ability to cache runner software in windows VMs like we do with linux VMs?

**Comment by gabriel-samfira** [comment]
Hi @Hdom 

All of these sound reasonable. Adding service accounts to runners is a very sharp knife. If you add them, make sure you use them with private repos or workflows that are not triggered by PRs.

@fabi200123 , could you have a look pls?

**Comment by fabi200123** [comment]
Will look over it and add a PR regarding these

**Comment by Hdom** [comment]
@fabi200123 @gabriel-samfira there's actually one more thing, there was a recent github outage that caused degraded download speeds causing our windows VMs to fail to download the runner software before the timeout period.

Could we add the ability to cache runner software in windows VMs like we do with linux VMs?

**Comment by gabriel-samfira** [comment]
That is a good idea.

**Comment by gabriel-samfira** [comment]
@Hdom 

Could you give #33 a try and see if it fits your needs?

**Comment by Hdom** [comment]
@gabriel-samfira Looks good from first inspection, resolves the first 3 asks (display, disk labels/type, and service account), I will pull it down and give it a try.

**Comment by fabi200123** [comment]
@Hdom Currently working on adding runner software caching to windows startup script as well. Will do a PR for that as well in a couple of days.
